### ISSUE TITLE
News Widget extension compatibility

### ISSUE THREAD

**Issue by DursunCanPoyraz** [justoverclockl/hot-discussions-cards#1]
Can you set it to appear under the news widget extension? Or can you fix the extra space between the news widget?

https://github.com/afrux/news-widget

![image](https://user-images.githubusercontent.com/74768208/147824151-4057bdca-4369-4713-b0bf-2b24ba5beb53.png)

**Comment by justoverclockl** [comment]
yes i will do this asap, meanwhile you can put

```
.cards-wrapper {
    margin-bottom: -40px;
}
```

**Comment by justoverclockl** [comment]
fixed https://github.com/justoverclockl/hot-discussions-cards/releases/tag/0.1.3
